# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera3d_interfaces.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import proto_build.sensor_msgs_pb2 as sensor__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera3d_interfaces.proto',
  package='camera3d_interfaces',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63\x61mera3d_interfaces.proto\x12\x13\x63\x61mera3d_interfaces\x1a\x11sensor_msgs.proto\"\xec\x01\n\x0eRGBDCameraData\x12!\n\x05\x63olor\x18\x01 \x01(\x0b\x32\x12.sensor_msgs.Image\x12!\n\x05\x64\x65pth\x18\x02 \x01(\x0b\x32\x12.sensor_msgs.Image\x12,\n\npointcloud\x18\x03 \x01(\x0b\x32\x18.sensor_msgs.PointCloud2\x12\x32\n\x11\x63olor_camera_info\x18\x04 \x01(\x0b\x32\x17.sensor_msgs.CameraInfo\x12\x32\n\x11\x64\x65pth_camera_info\x18\x05 \x01(\x0b\x32\x17.sensor_msgs.CameraInfob\x06proto3'
  ,
  dependencies=[sensor__msgs__pb2.DESCRIPTOR,])




_RGBDCAMERADATA = _descriptor.Descriptor(
  name='RGBDCameraData',
  full_name='camera3d_interfaces.RGBDCameraData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='camera3d_interfaces.RGBDCameraData.color', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth', full_name='camera3d_interfaces.RGBDCameraData.depth', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointcloud', full_name='camera3d_interfaces.RGBDCameraData.pointcloud', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color_camera_info', full_name='camera3d_interfaces.RGBDCameraData.color_camera_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='depth_camera_info', full_name='camera3d_interfaces.RGBDCameraData.depth_camera_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=306,
)

_RGBDCAMERADATA.fields_by_name['color'].message_type = sensor__msgs__pb2._IMAGE
_RGBDCAMERADATA.fields_by_name['depth'].message_type = sensor__msgs__pb2._IMAGE
_RGBDCAMERADATA.fields_by_name['pointcloud'].message_type = sensor__msgs__pb2._POINTCLOUD2
_RGBDCAMERADATA.fields_by_name['color_camera_info'].message_type = sensor__msgs__pb2._CAMERAINFO
_RGBDCAMERADATA.fields_by_name['depth_camera_info'].message_type = sensor__msgs__pb2._CAMERAINFO
DESCRIPTOR.message_types_by_name['RGBDCameraData'] = _RGBDCAMERADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RGBDCameraData = _reflection.GeneratedProtocolMessageType('RGBDCameraData', (_message.Message,), {
  'DESCRIPTOR' : _RGBDCAMERADATA,
  '__module__' : 'camera3d_interfaces_pb2'
  # @@protoc_insertion_point(class_scope:camera3d_interfaces.RGBDCameraData)
  })
_sym_db.RegisterMessage(RGBDCameraData)


# @@protoc_insertion_point(module_scope)
