from .build import SERVER_REGISTRY, build_server
from .rgbdmaskrcnn_trt import RGBDMaskRCNNTensorRTServicer
from .rgbmaskrcnn_torch import RGBMaskRCNNTorchServicer
from .rgbdmaskrcnn_torch import RGBDMaskRCNNTorchServicer